[en]
  title = "BrainDump"
  LanguageName = "English"
  weight = 1

[pt]
  title = "BrainDump" # just for the sake of showing this is possible
  LanguageName = "PortuguÃªs"
  weight = 2

  # tip: assign the default language the lowest Weight
