
# My work output
[[main]]
  parent = "Output"
  name = "Python dumps"
  url = "/series/diary-of-a-flawed-pythonista/"

[[main]]
  parent = "Output"
  name = "Linux commands cheatsheets"
  url = "/series/linux_cheatsheet/"

[[main]]
parent = "Output"
name = "sysAdmin cheatsheets"
url = "/tags/sysAdmin/"

[[main]]
parent = "Output"
name = "CCSP exam prep notes"
url = "/tags/ccsp/"

# Stuff I read

[[main]]
parent = "Input"
name = "Books to read again"
url = "post/books-list/"

[[main]]
parent = "Input"
name = "Favorite quotes"
url = "post/saved-quotes"

[[main]]
parent = "Input"
name = "Favorites Poems"
url = "/series/poems/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://diogo-pessoa.github.io/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
