
# Work brainDumps
[[main]]
  parent = "WorkHacks"
  name = "Python stuff"
  url = "/series/diary-of-a-flawed-pythonista/"

[[main]]
parent = "WorkHacks"
name = "sysAdmin"
url = "/tags/sysAdmin/"

[[main]]
parent = "WorkHacks"
name = "RCAs"
url = "/series/rcas/"

[[main]]
parent = "WorkHacks"
name = "CCSP Study drafts"
url = "/tags/ccsp/"

# personal brainDumps

[[main]]
parent = "other Great stuff"
name = "Books to read again"
url = "post/books-list/"

[[main]]
parent = "other Great stuff"
name = "Favorite quotes"
url = "post/saved-quotes"

[[main]]
parent = "other Great stuff"
name = "poems to remember"
url = "/series/poems/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://diogo-pessoa.github.io/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
